### ISSUE TITLE
it does not support utf-8 character sets

### ISSUE THREAD

**Issue by lospringliu** [grinstead/makeQrCode#1]
if I put some Chinese characters, it generate nothing

**Comment by grinstead** [comment]
Could you provide example text? It successfully generated the code below when I passed "你好。我的名字是Joe"
<img width="320" alt="image" src="https://user-images.githubusercontent.com/2280216/119834105-a756f880-becd-11eb-803a-e9e5bb3c7ffd.png">

**Comment by grinstead** [comment]
I'm going to mark this as closed. My guess is that you were pre-encoding the data to utf-8, however that is unnecessary. Just pass the plain javascript string into the function and the system will encode it for you.
